spring.application.name=SecurityApplication

spring.datasource.url=jdbc:mysql://localhost:3306/security-app?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#security configs
#spring.security.user.name=anee
#spring.security.user.password=pass
jwt.secretKey=bhhkjhljioe3hkbcljpehikbnxljkpjciubkhbclkpjhcir3khblckpjcirgvkbkjpjifgibjbdbdhbefbbsf4
#spring.security.oauth2.client.registration.google.client-id=345506087484-sg7nqv5dtd207t0tv1ke0rbnvq5ld7nf.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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

deploy.env = development